package:
  name: isatools
  version: "0.10.2"

source:
  url: https://files.pythonhosted.org/packages/c8/f9/20ef1b70655bdaeff8a442c49e39ffc1bf15b0a875520b0d17ceba74fe5f/isatools-0.10.2.tar.gz
  sha256: f704ee6f130906101a3628479847f4ad22ca0b60a13bbd772d387b2b2c9b9d9d

build:
  skip: True # [py27]
  number: 0
  entry_points:
    - isatools = isatools:main

requirements:
  host:
    - python
    - setuptools
    - numpy
    - jsonschema
    - pandas ==0.20
    - networkx
    - lxml
    - requests
    - chardet
    - iso8601
    - jinja2
    - beautifulsoup4
    - mzml2isa
    - biopython
    - progressbar2

  run:
    - python
    - numpy
    - jsonschema
    - pandas ==0.20
    - networkx
    - lxml
    - requests
    - chardet
    - iso8601
    - jinja2
    - beautifulsoup4
    - mzml2isa
    - biopython
    - progressbar2
    - libgcc

test:
  # Python imports
  imports:
    - isatools
    - isatools.convert
    - isatools.create
    - isatools.errors
    - isatools.io
    - isatools.net

about:
  home: https://github.com/ISA-tools/isa-api
  license: CPAL
  summary: 'Metadata tracking tools help to manage an increasingly diverse set of life science, environmental and biomedical experiments'
  license_family: OTHER
